### ISSUE TITLE
QueueParties always return nil

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#13]
@steven4547466 
Oops forgot to screenshot it

**Comment by steven4547466** [comment]
Commit https://github.com/steven4547466/MatchmakingService/commit/f27fefcd7585096a8c6e7c015e8895ccd5521d0b should fix this issue.

**Comment by iamEvanYT** [comment]
Uhh i think this issue is not fixed. @steven4547466 
this should not be closed

**Comment by iamEvanYT** [comment]
When I am trying to queue a party:
![Screenshot 2021-12-22 at 6 40 20 PM](https://user-images.githubusercontent.com/47493765/147140057-7c12829d-9d43-4f8c-9da0-b3d659b25b1b.png)

**Comment by steven4547466** [comment]
Can you show me your code? QueueParty doesn't return 3 values.

**Comment by iamEvanYT** [comment]
```Success,A,B = MatchmakingService:QueueParty(playersInParty, "unranked", QueueId)```
i thought it returned 3 values...

**Comment by iamEvanYT** [comment]
https://steven4547466.github.io/MatchmakingService/maindocs/#queueing-a-party

**Comment by steven4547466** [comment]
Hm, it should return 3 values if the first value is false actually. I'll look into why that's not working.

**Comment by steven4547466** [comment]
I see why those are nil. Are you intentionally making it return false, or is it just always returning false?

**Comment by iamEvanYT** [comment]
no. its always false when i called it.

**Comment by steven4547466** [comment]
I've updated the documentation to inform that the second and third values are nil if the first value is true.

https://steven4547466.github.io/MatchmakingService/maindocs/#queueing-a-party

I've also added a change so that the second values under that condition return properly.

If it's always returning false, first update to 4.2.4 (which I just released) and if it still happens can you show me the output and your code? There must be a different error happening.

**Comment by iamEvanYT** [comment]
ok

**Comment by iamEvanYT** [comment]
is V4.2.4 on [https://web.roblox.com/library/8267761365/MatchmakingService-Update](https://www.roblox.com/library/8267761365/MatchmakingService-Update) this?

**Comment by iamEvanYT** [comment]
its returning ```false,nil,nil``` again.

**Comment by iamEvanYT** [comment]
when i try to join again: 
![Screenshot 2021-12-22 at 7 11 51 PM](https://user-images.githubusercontent.com/47493765/147143451-ec8e843b-ba01-42b5-be15-ba8f727f1d54.png)
returns ```nil,nil,nil```
I am using ```require(8267761365)).GetSingleton()```

**Comment by iamEvanYT** [comment]
Oops sorry!
after a bit of printing, I think I gave the userIds instead of the player object in QueueParty.
I now used QueuePartyId and It works fine.
Thank you for all your help!

**Comment by steven4547466** [comment]
Sorry I couldn't respond sooner. Good to see you got it all solved though.
